### ISSUE TITLE
Query regarding Convert SVG to VGG 🦄

### ISSUE THREAD

**Issue by Neilblaze** [verygoodgraphics/vgg_svg_parser#2]
Hi @harry75369 👋🏼, My name is Pratyay & I'm redirecting from [here](https://summer-ospp.ac.cn/org/prodetail/246540050). I'm interested to know more about the project — "_Convert SVG to VGG_" and for the same, how can I get started?

I fulfill pretty much all of the requirements including,

- I'm familiar with JavaScript/TS.
- I have a decent understanding of vector graphics (from my Computer Graphics course curriculum) and have worked with SVGs before.
- I'm excited to learn the VGG format standards and I want to engage in communication to learn more about it.

You can validate my work by visiting my [GitHub](https://github.com/neilblaze) and checking out my past contributions. Rest aside, as I get more familiar with the aforementioned, I'll try to identify issues in the VGG format standards + suggest modifications if possible.

And also, most importantly, *is there any communication channel* that I can join to stay updated? 

Thanks!

**Comment by harry75369** [comment]
Hi Pratyay, Thanks for your interests in VGG and this OSPP project. There is a Discord channel that our team could be reached, and you can join in with this link https://discord.gg/89fFapjfgM

As for the OSPP, you can apply for our projects according to their rules: https://summer-ospp.ac.cn/help/en/student/, but it goes slowly so I won't be able to receive any applications until June.

**Comment by Neilblaze** [comment]
Thank you @harry75369 for the info, I've joined the discord. See you there!
